const CONFIG={nome:"Barbearia Template",slogan:"Seu estilo começa aqui.",descricao:"Um espaço pensado para quem valoriza um bom corte, atendimento de qualidade e personalidade em cada detalhe.",whatsapp:"5500000000000",telefone:"(00) 00000-0000",instagram:"@barbearia",instagramUrl:"https://instagram.com/",endereco:"Rua Exemplo, 123 — Centro",mapQuery:"Rua Exemplo, 123 Centro",servicos:[{nome:"Corte",descricao:"Corte personalizado com acabamento preciso.",preco:"R$ 40",duracao:"45 min"},{nome:"Barba",descricao:"Barba desenhada com cuidado e acabamento.",preco:"R$ 30",duracao:"30 min"},{nome:"Corte + Barba",descricao:"Experiência completa para renovar o visual.",preco:"R$ 65",duracao:"75 min"},{nome:"Acabamento",descricao:"Detalhes e finalização para manter o corte.",preco:"R$ 20",duracao:"20 min"},{nome:"Sobrancelha",descricao:"Acabamento discreto e alinhado.",preco:"R$ 15",duracao:"15 min"},{nome:"Combo Premium",descricao:"Serviço completo para uma experiência especial.",preco:"R$ 80",duracao:"90 min"}],horarios:[["Segunda","Fechado"],["Terça","09:00 – 19:00"],["Quarta","09:00 – 19:00"],["Quinta","09:00 – 20:00"],["Sexta","09:00 – 20:00"],["Sábado","08:00 – 18:00"],["Domingo","Fechado"]],galeria:["Ambiente","Cortes","Detalhes","Experiência"]};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function applyConfig(){document.title=CONFIG.nome;$$("[data-config]").forEach(el=>{const key=el.dataset.config;if(CONFIG[key]!==undefined)el.textContent=CONFIG[key]});$$("[data-config-link='instagram']").forEach(el=>el.href=CONFIG.instagramUrl);$$(".whatsapp-link").forEach(el=>el.href="https://wa.me/"+CONFIG.whatsapp+"?text="+encodeURIComponent("Olá! Gostaria de agendar um horário."));$(".map-link").href="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(CONFIG.mapQuery))}
function renderServices(){const list=$("#services-list"),select=$("#booking-service");CONFIG.servicos.forEach((s,i)=>{const card=document.createElement("article");card.className="service-card";card.innerHTML="<h3>"+s.nome+"</h3><p>"+s.descricao+"</p><div class='service-meta'><span class='price'>"+s.preco+"</span><span class='duration'>"+s.duracao+"</span></div>";list.appendChild(card);const option=document.createElement("option");option.value=i;option.textContent=s.nome+" — "+s.preco;select.appendChild(option)})}
function renderHours(){const list=$("#hours-list");CONFIG.horarios.forEach(([day,time])=>{const row=document.createElement("div");row.className="hours-row";row.innerHTML="<span>"+day+"</span><span>"+time+"</span>";list.appendChild(row)})}
function renderGallery(){const list=$("#gallery-list");CONFIG.galeria.forEach((label,i)=>{const item=document.createElement("figure");item.className="gallery-item";item.setAttribute("aria-label","Imagem de "+label);item.innerHTML="<span>0"+(i+1)+" • "+label+"<\/span>";list.appendChild(item)})}
function setupMenu(){const button=$(".menu-toggle"),nav=$("#main-menu");button.addEventListener("click",()=>{const open=nav.classList.toggle("open");button.setAttribute("aria-expanded",String(open));button.setAttribute("aria-label",open?"Fechar menu":"Abrir menu")});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");button.setAttribute("aria-expanded","false");button.setAttribute("aria-label","Abrir menu")}))}
function setupBooking(){const date=$("#booking-date"),time=$("#booking-time"),service=$("#booking-service"),summary=$("#booking-summary"),times=["09:00","09:45","10:30","11:15","13:30","14:15","15:00","15:45","16:30","17:15"];const update=()=>{time.innerHTML="<option value=''>Selecione</option>";if(date.value)times.forEach(t=>{const o=document.createElement("option");o.value=t;o.textContent=t;time.appendChild(o)});const s=CONFIG.servicos[service.value];summary.textContent=date.value&&time.value&&s?s.nome+" • "+date.value.split("-").reverse().join("/")+" • "+time.value+" • "+s.preco:"Selecione os dados acima."};date.min=new Date().toISOString().split("T")[0];[date,time,service].forEach(el=>el.addEventListener("change",update));$("#booking-form").addEventListener("submit",e=>{e.preventDefault();if(!date.value||!time.value||!service.value){summary.textContent="Preencha serviço, data e horário.";return}showToast("Agendamento demonstrativo confirmado.");update()})}
function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3200)}
applyConfig();renderServices();renderHours();renderGallery();setupMenu();setupBooking();